import { Link } from "@tanstack/react-router";
import { ArrowRight, BookOpenCheck, Check, ClipboardCheck, FileSearch, GraduationCap, ShieldCheck, Target } from "lucide-react";
import { useState } from "react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { Cta, DomainGrid, Label, PageHero, Reveal } from "@/components/site/Shared";
import team from "@/assets/equipe-laboratoire.webp";
import conseil from "@/assets/conseil-formation.webp";
import audit from "@/assets/audit-expertise.webp";
import { domains, stats } from "@/data/site";
import { faq } from "@/data/faq";

export function AboutPage(){const timeline=["Création en 2014","Développement des analyses spécialisées","Structuration du groupe : ELAM, ELAM Sahara et IQUALAB","Maillage national : 4 agences et 10+ points de proximité"];const capabilities=["Analyses bactériologiques","Analyses physico-chimiques","Détection des contaminants","Authenticité","Allergènes","Métaux lourds"];return <><PageHero dark label="ACCUEIL / À PROPOS" title="À propos de QualiUp" text="Un partenaire scientifique de proximité au service de la qualité, de la sécurité et de la confiance." image={team}/><section className="container-site section-pad grid gap-14 lg:grid-cols-2"><div><Label>[ 01 ] NOTRE HISTOIRE</Label><h2 className="mt-4 text-4xl font-bold">Une ambition construite autour de la fiabilité</h2><p className="mt-5 leading-8 text-muted-foreground">Depuis sa création en 2014, QualiUp s’affirme comme un véritable partenaire de l’industrie agroalimentaire. Notre développement répond à une même volonté : apporter une expertise claire, rigoureuse et accessible.</p></div><ol className="border-l-2 border-primary/30 pl-8">{timeline.map((x,i)=><li className="relative pb-9" key={x}><span className="absolute -left-[2.58rem] grid size-5 place-items-center rounded-full bg-primary text-[9px] text-white">{i+1}</span><strong className="font-display text-lg">{x}</strong></li>)}</ol></section><section className="bg-surface section-pad"><div className="container-site"><Label>[ 02 ] CAPACITÉS ANALYTIQUES</Label><h2 className="mt-4 text-4xl font-bold">Une lecture complète de vos matrices</h2><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{capabilities.map((x,i)=><div className="rounded-2xl border bg-background p-7"><span className="font-mono text-xs text-primary">CAP-0{i+1}</span><h3 className="mt-3 text-xl font-bold">{x}</h3></div>)}</div></div></section><Values/><Numbers/><Cta/></>}
function Values(){const v=[["Précision","Des protocoles maîtrisés et une attention constante portée à chaque étape."],["Fiabilité","Des données cohérentes, tracées et présentées avec clarté."],["Réactivité","Une équipe disponible pour comprendre le besoin et orienter la demande."],["Proximité","Un réseau national et des interlocuteurs proches de vos activités."]];return <section className="container-site section-pad"><Label>[ 03 ] NOS VALEURS</Label><div className="mt-9 grid gap-5 md:grid-cols-4">{v.map(([a,b])=><div className="group rounded-2xl border p-6 transition hover:-translate-y-2 hover:border-primary hover:shadow-soft"><h3 className="text-2xl font-bold group-hover:text-primary">{a}</h3><p className="mt-4 text-sm leading-6 text-muted-foreground">{b}</p></div>)}</div></section>}
function Numbers(){return <section className="bg-navy py-12 text-white"><div className="container-site grid grid-cols-2 gap-8 md:grid-cols-5">{stats.map(x=><div><b className="font-mono text-4xl">{x.value}</b><p className="mt-2 text-xs text-primary">{x.label}</p></div>)}</div></section>}
export function AnalysesPage(){const [i,setI]=useState(0),d=domains[i]!;return <><PageHero label="[ PRESTATIONS ] ANALYSES" title="Prestations d’analyses" text="Un large panel de tests spécialisés pour chaque secteur."/><section className="container-site section-pad"><div className="flex flex-wrap gap-2">{domains.map((x,j)=><button onClick={()=>setI(j)} className={`rounded-full px-4 py-2 text-sm font-semibold ${i===j?'bg-secondary text-white':'border'}`}><x.icon className="mr-1 inline size-4"/>{x.title}</button>)}</div><div className="mt-8 grid overflow-hidden rounded-3xl bg-navy text-white lg:grid-cols-2"><img src={d.image} alt="" className="h-full min-h-96 w-full object-cover"/><div className="p-9 lg:p-12"><Label>APERÇU SECTEUR</Label><h2 className="mt-4 text-4xl font-bold">{d.title}</h2><p className="mt-5 leading-7 text-white/70">{d.intro}</p><ul className="mt-6 grid gap-2 sm:grid-cols-2">{d.categories.flatMap(x=>x.items).slice(0,4).map(x=><li><Check className="mr-2 inline size-4 text-primary"/>{x}</li>)}</ul><Button className="mt-8" asChild><Link to="/prestations/$slug" params={{slug:d.slug}}>Voir le domaine <ArrowRight/></Link></Button></div></div></section><section className="bg-surface section-pad"><div className="container-site"><Label>[ FAMILLES ] TYPES D’ANALYSES</Label><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{["Microbiologie","Physico-chimie","Contaminants","Allergènes","Authenticité","Métaux lourds"].map(x=><div className="rounded-2xl border bg-white p-7"><FlaskIcon/><h3 className="mt-4 text-xl font-bold">{x}</h3></div>)}</div></div></section><section className="container-site section-pad"><DomainGrid limit={7}/></section><Cta/></>}
function FlaskIcon(){return <span className="grid size-11 place-items-center rounded-xl bg-green-soft text-primary"><FileSearch/></span>}
export function ServicesPage(){const pillars=[{title:"Analyses",icon:FileSearch,text:"Sept domaines pour contrôler les matrices, surveiller les risques et étayer vos décisions.",to:"/prestations-analyses"},{title:"Conseil et Formation",icon:GraduationCap,text:"Des accompagnements sur mesure pour faire vivre la qualité au quotidien.",to:"/conseil-formation"},{title:"Audit et Expertise",icon:ClipboardCheck,text:"Une lecture structurée de vos pratiques et des recommandations exploitables.",to:"/audit-expertise"}];return <><PageHero label="[ SERVICES ]" title="Trois piliers, une exigence commune" text="QualiUp réunit analyses, accompagnement et expertise pour répondre aux enjeux de votre activité."/><section className="container-site section-pad grid gap-6 lg:grid-cols-3">{pillars.map((p,i)=><Link to={p.to} className="group min-h-[430px] rounded-3xl border p-8 shadow-soft transition hover:-translate-y-2"><p className="font-mono text-xs text-primary">PILIER 0{i+1}</p><p.icon className="mt-12 size-12 text-secondary"/><h2 className="mt-6 text-3xl font-bold">{p.title}</h2><p className="mt-5 leading-7 text-muted-foreground">{p.text}</p><span className="mt-8 inline-flex gap-2 font-semibold text-primary">Explorer <ArrowRight/></span></Link>)}</section><Cta/></>}
export function AdvicePage(){const services=["HACCP","ISO 22000","Bonnes pratiques d’hygiène","Plan de maîtrise sanitaire","Formation hygiène alimentaire"];return <><PageHero label="[ ACCOMPAGNEMENT ]" title="Conseil et Formation" text="Transformez les exigences qualité en pratiques comprises, appliquées et durables." image={conseil}/><section className="container-site section-pad"><Label>[ 01 ] NOS ACCOMPAGNEMENTS</Label><div className="mt-8 grid gap-4 md:grid-cols-5">{services.map((x,i)=><div className="rounded-2xl border p-6"><span className="font-mono text-xs text-primary">0{i+1}</span><h3 className="mt-4 font-bold">{x}</h3></div>)}</div></section><Process title="Comment se déroule une formation" steps={["Diagnostic des besoins","Programme sur mesure","Formation sur site","Évaluation et suivi"]}/><Benefits/><Cta/></>}
export function AuditPage(){return <><PageHero dark label="[ EXPERTISE ]" title="Audit et Expertise" text="Évaluer avec méthode, comprendre les écarts et définir un plan d’action réaliste." image={audit}/><section className="container-site section-pad grid gap-12 lg:grid-cols-2"><div><Label>[ 01 ] NOS AUDITS</Label><h2 className="mt-4 text-4xl font-bold">Une checklist reliée à votre réalité</h2><div className="mt-8 space-y-4">{["Audit hygiène","Audit fournisseurs","Diagnostic de conformité","Audit des process de production"].map(x=><div className="flex items-center gap-3 rounded-xl border p-4"><Check className="text-primary"/><b>{x}</b></div>)}</div></div><div className="grid place-items-center rounded-3xl bg-blue-soft p-8"><div className="grid size-60 place-items-center rounded-full border-[18px] border-secondary"><span className="text-center"><b className="font-mono text-5xl text-secondary">100%</b><small className="mt-2 block">lecture structurée</small></span></div></div></section><Process title="Des livrables directement exploitables" steps={["Rapport détaillé","Points forts","Axes d’amélioration","Plan d’actions"]}/><Cta/></>}
function Process({title,steps}:{title:string;steps:string[]}){return <section className="section-pad bg-surface"><div className="container-site"><Label>[ MÉTHODE ]</Label><h2 className="mt-4 text-4xl font-bold">{title}</h2><div className="mt-10 grid gap-4 md:grid-cols-4">{steps.map((x,i)=><div className="rounded-2xl bg-white p-6 shadow-soft"><span className="font-mono text-primary">0{i+1}</span><h3 className="mt-5 text-lg font-bold">{x}</h3></div>)}</div></div></section>}
function Benefits(){const items=[{Icon:ShieldCheck,title:"Conformité"},{Icon:BookOpenCheck,title:"Montée en compétences"},{Icon:Target,title:"Confiance clients"}];return <section className="container-site section-pad grid gap-5 md:grid-cols-3">{items.map(({Icon,title})=><div key={title} className="rounded-2xl border p-7"><Icon className="text-primary"/><h3 className="mt-5 text-xl font-bold">{title}</h3></div>)}</section>}
export function FaqPage(){const [q,setQ]=useState(''),[cat,setCat]=useState('Tous');const cats=["Tous","Général","Analyses","Prélèvements","Résultats et rapports","Conseil et Audit"];const shown=faq.filter(([c,x])=>(cat==='Tous'||c===cat)&&x.toLowerCase().includes(q.toLowerCase()));return <><PageHero label="[ AIDE ]" title="Questions fréquentes" text="Trouvez rapidement une réponse sur les analyses, prélèvements, rapports et accompagnements."/><section className="container-site section-pad"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Rechercher une question…" className="h-14 w-full rounded-full border px-6" aria-label="Rechercher une question"/><div className="mt-5 flex flex-wrap gap-2">{cats.map(x=><button onClick={()=>setCat(x)} className={`rounded-full px-4 py-2 text-sm ${cat===x?'bg-secondary text-white':'border'}`}>{x}</button>)}</div><Accordion type="single" collapsible className="mt-10">{shown.map(([c,x,a],i)=><AccordionItem value={`${i}-${x}`}><AccordionTrigger className="text-base"><span><small className="mr-3 font-mono text-primary">{c}</small>{x}</span></AccordionTrigger><AccordionContent className="max-w-3xl leading-7 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></section><Cta/></>}
