import { zodResolver } from "@hookform/resolvers/zod";
import { createServerFn } from "@tanstack/react-start";
import { Building2, CheckCircle2, Mail, MapPin, Phone } from "lucide-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label, PageHero } from "@/components/site/Shared";
import { agencies, company, domains } from "@/data/site";
const schema=z.object({full_name:z.string().min(2,"Indiquez votre nom complet"),company:z.string().optional(),email:z.string().email("Adresse email invalide"),phone:z.string().min(8,"Numéro de téléphone requis"),sector:z.string().min(1,"Choisissez un secteur"),request_type:z.string().min(1,"Choisissez le type de demande"),nearest_agency:z.string().optional(),message:z.string().min(10,"Précisez votre demande en quelques mots"),consent_accepted:z.literal(true,{errorMap:()=>({message:"Votre accord est requis"})})});
type FormData=z.infer<typeof schema>;
const submitRequest=createServerFn({method:"POST"}).inputValidator(schema).handler(async({data})=>{const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const tracking_code=`QU-${Math.floor(1000+Math.random()*9000)}`;const {error}=await supabaseAdmin.from("contact_requests").insert({...data,company:data.company||null,nearest_agency:data.nearest_agency||null,tracking_code});if(error)throw new Error("Enregistrement impossible");return{tracking_code}});
export function ContactPage(){const params=typeof window==='undefined'?new URLSearchParams():new URLSearchParams(window.location.search);const [code,setCode]=useState('');const [failure,setFailure]=useState('');const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<FormData>({resolver:zodResolver(schema),defaultValues:{sector:params.get('secteur')||'',request_type:params.get('type')||'',consent_accepted:false as true}});const onSubmit=async(data:FormData)=>{setFailure('');try{const r=await submitRequest({data});setCode(r.tracking_code)}catch{setFailure("Votre demande n’a pas pu être enregistrée. Appelez-nous ou réessayez.")}};return <><PageHero label="[ CONTACT ]" title="Contactez-nous" text="Une question, un échantillon à analyser, un devis ? Nos équipes vous répondent."/>
<section className="container-site section-pad grid items-start gap-10 lg:grid-cols-[1.2fr_.8fr]">{code?<div className="rounded-3xl border bg-green-soft p-12 text-center shadow-soft"><CheckCircle2 className="mx-auto size-16 text-primary"/><h2 className="mt-6 text-3xl font-bold">Votre demande a bien été enregistrée</h2><p className="mt-4 text-muted-foreground">Conservez votre code de suivi :</p><strong className="mt-3 block font-mono text-3xl text-secondary">{code}</strong></div>:<form onSubmit={handleSubmit(onSubmit)} className="rounded-3xl border bg-white p-6 shadow-soft sm:p-9"><Label>[ FORMULAIRE ]</Label><h2 className="mt-3 text-3xl font-bold">Décrivez votre besoin</h2><div className="mt-8 grid gap-5 sm:grid-cols-2"><Field label="Nom complet *" error={errors.full_name?.message}><Input {...register('full_name')}/></Field><Field label="Société"><Input {...register('company')}/></Field><Field label="Email *" error={errors.email?.message}><Input type="email" {...register('email')}/></Field><Field label="Téléphone *" error={errors.phone?.message}><Input type="tel" {...register('phone')}/></Field><Field label="Secteur *" error={errors.sector?.message}><Select {...register('sector')}><option value="">Choisir</option>{domains.map(x=><option value={x.slug}>{x.title}</option>)}<option value="autre">Autre</option></Select></Field><Field label="Type de demande *" error={errors.request_type?.message}><Select {...register('request_type')}><option value="">Choisir</option>{["Analyse","Devis","Conseil et formation","Audit","Autre"].map(x=><option>{x}</option>)}</Select></Field><Field label="Agence la plus proche"><Select {...register('nearest_agency')}><option value="">Choisir</option>{agencies.map(x=><option>{x.name}</option>)}</Select></Field><div/><Field label="Message *" error={errors.message?.message} wide><Textarea rows={6} {...register('message')}/></Field><label className="flex gap-3 text-sm sm:col-span-2"><input type="checkbox" {...register('consent_accepted')}/><span>J’accepte que mes données soient utilisées pour traiter ma demande, conformément à la loi 09-08.</span></label>{errors.consent_accepted&&<p className="text-sm text-destructive sm:col-span-2">{errors.consent_accepted.message}</p>}{failure&&<p role="alert" className="text-sm text-destructive sm:col-span-2">{failure}</p>}<Button disabled={isSubmitting} className="sm:col-span-2">{isSubmitting?'Envoi en cours…':'Envoyer ma demande'}</Button></div></form>}
<aside className="space-y-4"><ContactCard icon={Phone} title="Téléphone" text={company.phone} href={`tel:${company.phoneHref}`}/><ContactCard icon={Mail} title="Email général" text={company.email} href={`mailto:${company.email}`}/><ContactCard icon={Mail} title="Email technique" text={company.technicalEmail} href={`mailto:${company.technicalEmail}`}/><ContactCard icon={MapPin} title="Siège" text={company.address}/><div className="mt-8 rounded-2xl bg-navy p-6 text-white"><Building2 className="text-primary"/><h3 className="mt-4 text-xl font-bold">Rejoignez l’équipe</h3><a className="mt-3 block text-sm text-primary" href={`mailto:${company.recruitmentEmail}?subject=Candidature%20spontanée`}>{company.recruitmentEmail}</a></div></aside></section></>}
function Field({label,error,wide,children}:{label:string;error?:string|undefined;wide?:boolean;children:React.ReactNode}){return <label className={wide?'sm:col-span-2':''}><span className="mb-2 block text-sm font-semibold">{label}</span>{children}{error&&<small className="mt-1 block text-destructive">{error}</small>}</label>}
function Select(p:React.SelectHTMLAttributes<HTMLSelectElement>){return <select {...p} className="h-11 w-full rounded-md border bg-white px-3 text-sm"/>}
function ContactCard({icon:I,title,text,href}:{icon:typeof Phone;title:string;text:string;href?:string}){const inner=<><span className="grid size-11 place-items-center rounded-xl bg-green-soft text-primary"><I/></span><div><small className="text-muted-foreground">{title}</small><strong className="block">{text}</strong></div></>;return href?<a href={href} className="flex gap-4 rounded-2xl border p-5 shadow-soft">{inner}</a>:<div className="flex gap-4 rounded-2xl border p-5 shadow-soft">{inner}</div>}
