import { Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, Check, FileText, FlaskConical, PackageCheck } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Label } from "@/components/site/Shared";
import { domains, type Domain } from "@/data/site";

export function DomainPage({domain}:{domain:Domain}){const [tab,setTab]=useState(0);const idx=domains.findIndex(d=>d.slug===domain.slug),prev=domains[(idx+domains.length-1)%domains.length],next=domains[(idx+1)%domains.length];return <>
<section className="relative min-h-[620px] overflow-hidden text-white"><img src={domain.image} alt={`Analyses ${domain.title}`} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-linear-to-r from-navy via-navy/80 to-navy/20"/><div className="container-site relative z-10 flex min-h-[620px] max-w-4xl flex-col justify-center py-16"><p className="font-mono text-xs text-primary">ACCUEIL / PRESTATIONS / {domain.title.toUpperCase()}</p><domain.icon className="mt-8 size-12 text-primary"/><h1 className="mt-5 text-5xl font-extrabold sm:text-6xl">Analyses {domain.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/75">{domain.short}</p><Button className="mt-8 w-fit" asChild><Link to="/contact" search={{secteur:domain.slug}}>Demander un devis pour ce domaine <ArrowRight/></Link></Button></div></section>
<section className="container-site section-pad grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><Label>[ 01 ] ENJEUX DU SECTEUR</Label><h2 className="mt-4 text-4xl font-bold">Des données fiables pour mieux maîtriser vos décisions</h2></div><p className="text-lg leading-9 text-muted-foreground">{domain.intro} Nos équipes prennent le temps de qualifier votre demande et d’orienter le choix des analyses selon la matrice et l’objectif recherché.</p></section>
<section className="bg-surface section-pad"><div className="container-site"><Label>[ 02 ] CE QUE NOUS ANALYSONS</Label><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{domain.matrices.map((x,i)=><div className="rounded-2xl border bg-white p-6"><span className="font-mono text-xs text-primary">MAT-{String(i+1).padStart(2,'0')}</span><h3 className="mt-4 text-lg font-bold">{x}</h3></div>)}</div></div></section>
<section className="container-site section-pad"><Label>[ 03 ] PARAMÈTRES ANALYSÉS</Label><div className="mt-7 flex flex-wrap gap-2">{domain.categories.map((x,i)=><button onClick={()=>setTab(i)} className={`rounded-full px-4 py-2 text-sm font-semibold ${tab===i?'bg-secondary text-white':'border'}`}>{x.name}</button>)}</div><div className="report-lines mt-7 overflow-hidden rounded-2xl border">{domain.categories[tab].items.map((x,i)=><div className="flex items-center justify-between border-b p-5 last:border-0"><span className="font-semibold">{x}</span><span className="font-mono text-xs text-muted-foreground">{domain.categories[tab].name.toUpperCase().slice(0,5)}-{String(i+1).padStart(2,'0')}</span></div>)}</div></section>
<section className="bg-blue-soft py-16"><div className="container-site"><Label>[ 04 ] POUR QUI ?</Label><div className="mt-7 flex flex-wrap gap-3">{domain.clients.map(x=><span className="rounded-full bg-white px-5 py-3 font-semibold shadow-soft">{x}</span>)}</div></div></section>
<section className="container-site section-pad"><div className="grid gap-5 md:grid-cols-3">{[[PackageCheck,"Prélèvement","Conditions adaptées à la matrice"],[FlaskConical,"Analyse","Paramètres ciblés selon le besoin"],[FileText,"Rapport","Résultats structurés et lisibles"]].map(([I,t,d],i)=><div className="rounded-2xl border p-7"><I className="text-primary"/><span className="mt-6 block font-mono text-xs">ÉTAPE 0{i+1}</span><h3 className="mt-2 text-xl font-bold">{t as string}</h3><p className="mt-2 text-sm text-muted-foreground">{d as string}</p></div>)}</div></section>
<section className="section-pad bg-surface"><div className="container-site max-w-4xl"><Label>[ FAQ ]</Label><Accordion type="single" collapsible className="mt-6">{[["Comment préparer mon échantillon ?","Contactez notre équipe technique : les conditions dépendent de la matrice et des paramètres recherchés."],["Pouvez-vous réaliser le prélèvement ?","Un prélèvement sur site peut être organisé selon la demande et la localisation."],["Comment recevoir mon rapport ?","Le canal de transmission est défini avec votre interlocuteur lors de la prise en charge."]].map(([q,a],i)=><AccordionItem value={`${i}`}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent className="text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>
<section className="container-site section-pad"><div className="rounded-3xl bg-navy p-8 text-white sm:p-12"><Label>[ DEVIS ] {domain.title}</Label><h2 className="mt-4 text-4xl font-bold">Parlez-nous de votre matrice</h2><p className="mt-4 max-w-2xl text-white/70">Le domaine est déjà pré-sélectionné pour vous faire gagner du temps.</p><Button className="mt-7" asChild><Link to="/contact" search={{secteur:domain.slug,type:"Analyse"}}>Commencer ma demande <ArrowRight/></Link></Button></div></section>
<nav className="container-site mb-20 flex justify-between gap-4 border-t pt-8"><Link to="/prestations/$slug" params={{slug:prev.slug}} className="font-semibold"><ArrowLeft className="mr-2 inline"/> {prev.title}</Link><Link to="/prestations/$slug" params={{slug:next.slug}} className="text-right font-semibold">{next.title} <ArrowRight className="ml-2 inline"/></Link></nav>
</>}
