import { Link } from "@tanstack/react-router";
import { ArrowRight, Check, ChevronLeft, ChevronRight, ClipboardCheck, FileText, FlaskConical, MapPin, PackageCheck, Pause, Phone, Play, Snowflake, Star, Thermometer, Volume2, VolumeX } from "lucide-react";
import { motion } from "motion/react";
import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Cta, DomainGrid, Label, Reveal } from "@/components/site/Shared";
import heroVideo from "@/assets/hero-presentation.mp4.asset.json";
import heroPoster from "@/assets/hero-presentation-poster.jpg.asset.json";
import expertise from "@/assets/expertise-echantillons.webp";
import conseil from "@/assets/conseil-formation.webp";
import audit from "@/assets/audit-expertise.webp";
import careers from "@/assets/carrieres-microscope.webp";
import { agencies, company, stats, testimonials } from "@/data/site";
import { articles as articleData } from "@/data/articles";

export function HomePage(){return <>
  <Hero/><DataBand/><Expertise/><Domains/><SampleJourney/><Group/><AdviceAudit/><Testimonials/><Agencies/><News/><Careers/><Cta/>
</>}
function Hero(){const msgs=["Des résultats fiables pour décider avec confiance.","Une expertise scientifique au plus près de vos activités.","De l’échantillon au rapport, une traçabilité maîtrisée."];const [i,setI]=useState(0);useEffect(()=>{const t=setInterval(()=>setI(x=>(x+1)%3),4000);return()=>clearInterval(t)},[]);return <section className="molecule-grid relative overflow-hidden"><div className="container-site grid min-h-[720px] items-center gap-10 py-16 lg:grid-cols-[1.1fr_.9fr]"><div className="relative z-10"><p className="section-label">[ QU-2014 ] LABORATOIRE D’ANALYSES · MAROC</p><h1 className="mt-5 max-w-3xl text-5xl font-extrabold leading-[1.05] sm:text-6xl lg:text-7xl">Votre laboratoire agroalimentaire au Maroc <span className="text-gradient">de confiance</span></h1><motion.p key={i} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="mt-6 min-h-8 text-lg font-medium text-muted-foreground sm:text-xl">{msgs[i]}</motion.p><div className="mt-8 flex flex-wrap gap-3"><Button size="lg" asChild><Link to="/contact">Demander une analyse <ArrowRight/></Link></Button><Button size="lg" variant="outline" asChild><Link to="/prestations-analyses">Découvrir nos prestations</Link></Button></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-sm font-semibold">{["10+ ans","5 laboratoires","4 agences"].map(x=><span key={x}><Check className="mr-1 inline size-4 text-primary"/>{x}</span>)}</div></div><HeroVideo/></div></section>}
function HeroVideo(){const videoRef=useRef<HTMLVideoElement>(null);const [playing,setPlaying]=useState(false);const [muted,setMuted]=useState(false);const play=()=>{void videoRef.current?.play()};const pause=()=>videoRef.current?.pause();const toggleMute=()=>{const video=videoRef.current;if(!video)return;video.muted=!video.muted;setMuted(video.muted)};return <div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-8 -z-10 rounded-[42%_58%_48%_52%] bg-linear-to-br from-primary/20 to-secondary/20 blur-sm"/><video ref={videoRef} src={heroVideo.url} poster={heroPoster.url} playsInline preload="metadata" aria-label="Présentation de QualiUp par une porte-parole" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)} className="aspect-[4/5] w-full rounded-[38%_18%_34%_14%] object-cover shadow-float"/>{!playing&&<Button type="button" size="icon" onClick={play} aria-label="Lire la présentation" className="glass absolute inset-0 z-20 m-auto size-16 border border-background/60 text-primary shadow-float hover:scale-105"><Play className="size-7 fill-current"/></Button>}{playing&&<div className="absolute bottom-5 right-5 z-20 flex gap-2"><Button type="button" size="icon" variant="outline" onClick={pause} aria-label="Mettre la présentation en pause" className="glass border-background/60 shadow-soft"><Pause/></Button><Button type="button" size="icon" variant="outline" onClick={toggleMute} aria-label={muted?"Activer le son":"Couper le son"} className="glass border-background/60 shadow-soft">{muted?<VolumeX/>:<Volume2/>}</Button></div>}<Floating className="-left-5 top-20" icon={<FlaskConical/>} title="Échantillon QU-0427" value="✓ Conforme"/><Floating className="-right-3 bottom-28" icon={<ClipboardCheck/>} title="Microbiologie" value="Analyse terminée"/><Floating className="bottom-2 left-8" icon={<Thermometer/>} title="Chaîne du froid" value="4°C ✓"/></div>}
function Floating({className,icon,title,value}:{className:string;icon:React.ReactNode;title:string;value:string}){return <div className={`glass float-card absolute hidden rounded-2xl border border-white/60 p-4 shadow-float sm:block ${className}`}><div className="flex items-center gap-3"><span className="rounded-xl bg-green-soft p-2 text-primary">{icon}</span><div><p className="font-mono text-[10px] text-muted-foreground">{title}</p><strong className="text-sm">{value}</strong></div></div></div>}
function DataBand(){return <section className="relative overflow-hidden bg-navy py-10 text-primary-foreground"><div className="scan-line absolute inset-y-0 w-px bg-primary shadow-[0_0_24px_4px_#52A546]"/><div className="container-site grid grid-cols-2 gap-8 md:grid-cols-5">{stats.map(s=><div key={s.label}><strong className="font-mono text-4xl sm:text-5xl">{s.value}</strong><p className="mt-2 text-xs font-semibold uppercase tracking-wide text-primary">{s.label}</p></div>)}</div></section>}
function Expertise(){return <section className="container-site section-pad grid items-center gap-14 lg:grid-cols-2"><Reveal className="relative"><img loading="lazy" src={expertise} width="1400" height="1050" alt="Préparation précise d’échantillons au laboratoire" className="rounded-[2rem] object-cover shadow-soft"/><div className="absolute -bottom-7 right-5 grid size-36 place-items-center rounded-full border-[10px] border-green-soft bg-background text-center shadow-float"><span><b className="block font-display text-3xl text-primary">10+</b><small>années<br/>d’expérience</small></span></div></Reveal><Reveal><Label>[ 01 ] QUI SOMMES-NOUS</Label><h2 className="mt-4 text-4xl font-bold">La science au service de vos décisions</h2><p className="mt-6 leading-8 text-muted-foreground">Laboratoire agroalimentaire au Maroc, QualiUp est reconnu pour son expertise scientifique et technique. Spécialisés dans les analyses et essais techniques, nous accompagnons de nombreux secteurs en fournissant des résultats fiables et précis.</p><Protocol n="01" title="Laboratoire à la technologie avancée">Équipements modernes et méthodes maîtrisées pour des résultats fiables et reproductibles.</Protocol><Protocol n="02" title="Large panel de tests spécialisés">Agroalimentaire, agronomie, environnement, cosmétique et matrices spécifiques.</Protocol><Button variant="link" asChild><Link to="/a-propos">En savoir plus sur QualiUp <ArrowRight/></Link></Button></Reveal></section>}
function Protocol({n,title,children}:{n:string,title:string,children:React.ReactNode}){return <div className="mt-7 flex gap-4 border-t pt-5"><span className="font-mono text-sm text-primary">{n}</span><div><h3 className="text-lg font-bold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{children}</p></div></div>}
function Domains(){return <section className="bg-surface section-pad"><div className="container-site"><div className="mb-10 max-w-3xl"><Label>[ 02 ] NOS DOMAINES</Label><h2 className="mt-4 text-4xl font-bold sm:text-5xl">7 domaines d’analyses, une seule exigence : la fiabilité</h2></div><DomainGrid/></div></section>}
const steps=[["Prélèvement","Sur site ou dépôt",MapPin],["Transport","Chaîne du froid",Snowflake],["Réception & codification","Code de traçabilité unique",PackageCheck],["Analyse","Microbiologie, physico-chimie, contaminants",FlaskConical],["Rapport","Clair, fiable et exploitable",FileText]] as const;
function SampleJourney(){return <section className="section-pad overflow-hidden bg-blue-soft"><div className="container-site"><div className="text-center"><Label>[ 03 ] PARCOURS ÉCHANTILLON</Label><h2 className="mt-4 text-4xl font-bold">Une traçabilité continue, étape par étape</h2></div><div className="relative mt-14 grid gap-4 md:grid-cols-5"><div className="absolute left-[10%] right-[10%] top-9 hidden h-0.5 bg-border md:block"><motion.div className="h-full bg-primary" initial={{width:0}} whileInView={{width:"100%"}} viewport={{once:true}} transition={{duration:1.5}}/></div>{steps.map(([t,d,I],i)=><Reveal key={t} className="relative rounded-2xl border bg-background p-5 md:border-0 md:bg-transparent md:text-center"><div className="relative z-10 mx-auto mb-4 grid size-18 place-items-center rounded-full border-8 border-blue-soft bg-background text-secondary shadow-soft"><I/></div><p className="font-mono text-[10px] text-primary">ÉTAPE 0{i+1}</p><h3 className="mt-2 text-lg font-bold">{t}</h3><p className="mt-2 text-sm text-muted-foreground">{d}</p></Reveal>)}</div></div></section>}
function Group(){const groups=[{n:"ELAM",d:"Une référence incontournable dans les analyses en agronomie, agroalimentaire et environnement, ainsi que dans la fourniture d’expertises.",url:"https://elamlaboratory.com/"},{n:"ELAM Sahara",d:"La même exigence scientifique, portée par une présence de proximité dans le sud du Royaume.",url:"https://elamlaboratory.com/"},{n:"IQUALAB",d:"Membre du groupe QualiUp, Iqua’Lab se positionne comme un acteur majeur des analyses et tests pour l’agroalimentaire.",url:"https://iqualaboratory.com/"}];return <section className="container-site section-pad"><Label>[ 04 ] LE GROUPE</Label><div className="mt-4 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="max-w-2xl text-4xl font-bold">Trois expertises, une ambition commune</h2><p className="max-w-md text-muted-foreground">Un groupe structuré pour rapprocher la compétence analytique des entreprises partout au Maroc.</p></div><div className="mt-12 grid gap-6 lg:grid-cols-3">{groups.map((g,i)=><a target="_blank" rel="noreferrer" href={g.url} key={g.n} className="group relative min-h-96 overflow-hidden rounded-[5rem_5rem_1.5rem_1.5rem] border bg-background p-8 pt-20 shadow-soft"><div className="absolute inset-x-0 bottom-0 h-2 bg-linear-to-t from-secondary to-primary transition-all duration-700 group-hover:h-full"/><div className="relative z-10 transition-colors group-hover:text-primary-foreground"><span className="font-mono text-xs">FORMULE 0{i+1}</span><h3 className="mt-5 text-3xl font-bold">{g.n}</h3><p className="mt-5 leading-7 opacity-75">{g.d}</p><span className="mt-8 inline-flex items-center gap-2 font-semibold">Visiter le site <ArrowRight/></span></div></a>)}</div></section>}
function AdviceAudit(){return <section className="flex flex-col lg:flex-row"><ServicePanel color="bg-green-soft" image={conseil} title="Conseil et Formation" text="HACCP, ISO 22000, bonnes pratiques d’hygiène et programmes conçus pour vos équipes." to="/conseil-formation"/><ServicePanel color="bg-blue-soft" image={audit} title="Audit et Expertise" text="Diagnostics structurés, analyse des écarts et recommandations directement exploitables." to="/audit-expertise"/></section>}
function ServicePanel({color,image,title,text,to}:{color:string;image:string;title:string;text:string;to:string}){return <Link to={to} className={`group relative min-h-[550px] flex-1 overflow-hidden p-8 transition-all duration-500 hover:flex-[1.15] sm:p-12 ${color}`}><img loading="lazy" src={image} width="1400" height="1050" alt="" className="absolute inset-0 h-full w-full object-cover opacity-30 transition group-hover:scale-105"/><div className="absolute inset-0 bg-linear-to-t from-navy/85 via-navy/25 to-transparent"/><div className="absolute inset-x-8 bottom-10 text-primary-foreground sm:inset-x-12"><h2 className="text-4xl font-bold">{title}</h2><p className="mt-4 max-w-lg leading-7 text-primary-foreground/80">{text}</p><span className="mt-6 inline-flex items-center gap-2 font-semibold text-primary">Découvrir <ArrowRight/></span></div></Link>}
function Testimonials(){const [i,setI]=useState(0);const t=testimonials[i]!;return <section className="section-pad bg-navy text-primary-foreground"><div className="container-site"><div className="flex items-end justify-between gap-4"><div><Label>[ 05 ] TÉMOIGNAGES</Label><h2 className="mt-4 text-4xl font-bold">La confiance se mesure sur le terrain</h2></div><div className="hidden gap-2 sm:flex"><Button size="icon" variant="outline" onClick={()=>setI((i+2)%3)} aria-label="Avis précédent"><ChevronLeft/></Button><Button size="icon" variant="outline" onClick={()=>setI((i+1)%3)} aria-label="Avis suivant"><ChevronRight/></Button></div></div><motion.article key={i} initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} className="report-lines relative mt-10 max-w-4xl rounded-2xl bg-background p-7 text-foreground shadow-float sm:p-10"><div className="flex justify-between"><span className="font-mono text-xs text-secondary">AVIS-00{i+1}</span><span className="rotate-3 rounded-full border-2 border-primary px-3 py-1 text-xs font-bold text-primary">✓ VÉRIFIÉ</span></div><blockquote className="mt-8 font-display text-xl font-semibold leading-9 sm:text-2xl">“{t.text}”</blockquote><div className="mt-8 flex items-center gap-3"><span className="grid size-11 place-items-center rounded-full bg-secondary font-bold text-primary-foreground">{t.name.split(' ').map(x=>x[0]).join('')}</span><div><strong>{t.name}</strong><p className="text-xs text-muted-foreground">{t.role}</p></div></div></motion.article></div></section>}
function MoroccoMap(){return <svg viewBox="0 0 280 520" role="img" aria-label="Carte du Maroc incluant les provinces du Sud" className="mx-auto h-[440px] max-w-full"><path d="M104 16 169 29 199 57 188 98 204 126 185 151 180 201 153 231 156 280 143 314 141 356 119 389 111 431 91 476 70 503 47 488 54 446 67 403 67 360 83 319 85 270 103 229 96 190 109 151 91 116 104 79 86 45Z" fill="#EAF0FA" stroke="#254F9C" strokeWidth="4"/><MapDot x="118" y="55"/><MapDot x="110" y="125"/><MapDot x="93" y="220" big/><MapDot x="66" y="416"/></svg>}
function MapDot({x,y,big=false}:{x:string;y:string;big?:boolean}){return <><circle cx={x} cy={y} r={big?12:9} fill="#52A546" opacity=".22"><animate attributeName="r" values={big?"12;20;12":"9;16;9"} dur="2s" repeatCount="indefinite"/></circle><circle cx={x} cy={y} r={big?7:5} fill="#52A546" stroke="white" strokeWidth="3"/></>}
function Agencies(){const [i,setI]=useState(2),a=agencies[i]!;return <section className="section-pad bg-surface"><div className="container-site grid items-center gap-12 lg:grid-cols-2"><MoroccoMap/><div><Label>[ 06 ] NOTRE PRÉSENCE</Label><h2 className="mt-4 text-4xl font-bold">À vos côtés, du nord au sud du Royaume</h2><div className="mt-8 flex flex-wrap gap-2">{agencies.map((x,j)=><button key={x.name} onClick={()=>setI(j)} className={`rounded-full px-4 py-2 text-sm font-semibold ${i===j?'bg-secondary text-primary-foreground':'border bg-background'}`}>{x.name}{j===2?' · Siège':''}</button>)}</div><div className="mt-6 overflow-hidden rounded-2xl border bg-background shadow-soft"><iframe title={`Carte de ${a.name}`} src={a.map} className="h-56 w-full border-0" loading="lazy"/><div className="p-6"><h3 className="text-2xl font-bold">Agence de {a.name}</h3>{a.address&&<p className="mt-2 text-muted-foreground">{a.address}</p>}<div className="mt-5 flex flex-wrap gap-3"><Button asChild><a href={`tel:${a.phone.replace(/\s/g,'')}`}><Phone/>{a.phone}</a></Button><Button variant="outline" asChild><a href={`mailto:${company.technicalEmail}?subject=Demande%20d'information`}>Envoyer un email</a></Button></div></div></div></div></div></section>}
function News(){return <section className="container-site section-pad"><div className="flex flex-wrap items-end justify-between gap-4"><div><Label>[ 07 ] RESSOURCES</Label><h2 className="mt-4 text-4xl font-bold">Actualités & expertise</h2></div><Button variant="link" asChild><Link to="/actualites">Toutes les actualités <ArrowRight/></Link></Button></div><div className="mt-10 grid gap-6 lg:grid-cols-2"><ArticleCard a={articleData[0]!} big/><div className="grid gap-6">{articleData.slice(1).map(a=><ArticleCard a={a} key={a.slug}/>)}</div></div></section>}
function ArticleCard({a,big=false}:{a:(typeof articleData)[number];big?:boolean}){return <Link to="/actualites/$slug" params={{slug:a.slug}} className={`group grid overflow-hidden rounded-2xl border bg-background shadow-soft ${big?'':'sm:grid-cols-[.8fr_1.2fr]'}`}><img loading="lazy" src={a.image} alt="" className={`h-full w-full object-cover transition group-hover:scale-105 ${big?'aspect-[16/10]':'min-h-52'}`}/><div className="p-6"><div className="flex gap-3 font-mono text-[10px] text-muted-foreground"><span className="text-primary">{a.category}</span><span>{a.date}</span><span>{a.read}</span></div><h3 className="mt-3 text-xl font-bold group-hover:text-secondary">{a.title}</h3></div></Link>}
function Careers(){return <section className="signature-bg overflow-hidden text-primary-foreground"><div className="container-site grid items-center gap-8 pt-12 lg:grid-cols-2"><div className="pb-12"><p className="font-mono text-xs">[ CARRIÈRES ]</p><h2 className="mt-4 text-4xl font-bold">Grandissez avec un laboratoire dynamique et innovant</h2><p className="mt-5 leading-7 text-primary-foreground/80">Envoyez-nous votre CV et faites partie de notre équipe.</p><Button className="mt-7 bg-background text-navy hover:bg-background/90" asChild><a href={`mailto:${company.recruitmentEmail}?subject=Candidature%20spontanée`}>Envoyer mon CV <ArrowRight/></a></Button></div><img loading="lazy" src={careers} width="1400" height="1050" alt="Technicien marocain travaillant au microscope" className="max-h-[430px] w-full self-end rounded-t-[6rem] object-cover object-top"/></div></section>}
