import { Link } from "@tanstack/react-router";
import { ArrowRight, ChevronRight } from "lucide-react";
import { motion } from "motion/react";
import { Button } from "@/components/ui/button";
import { domains } from "@/data/site";
export const Reveal=({children,className=""}:{children:React.ReactNode,className?:string})=><motion.div className={className} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:"-80px"}} transition={{duration:.55}}>{children}</motion.div>;
export function Label({children}:{children:React.ReactNode}){return <p className="section-label">{children}</p>}
export function PageHero({label,title,text,image,dark=false}:{label:string;title:string;text:string;image?:string;dark?:boolean}){return <section className={`overflow-hidden ${dark?'bg-navy text-primary-foreground':'molecule-grid bg-blue-soft'}`}><div className={`container-site grid items-center gap-12 py-16 lg:py-24 ${image?'lg:grid-cols-2':''}`}><div><p className="font-mono text-xs text-primary">{label}</p><h1 className="mt-4 max-w-3xl font-display text-4xl font-extrabold leading-tight sm:text-5xl lg:text-6xl">{title}</h1><p className={`mt-6 max-w-2xl text-lg leading-8 ${dark?'text-primary-foreground/70':'text-muted-foreground'}`}>{text}</p></div>{image&&<img src={image} alt="" className="aspect-[4/3] w-full rounded-[1.75rem] object-cover shadow-float"/>}</div></section>}
export function Cta(){return <section className="container-site section-pad"><div className="petri overflow-hidden rounded-[1.75rem] border border-border bg-green-soft px-6 py-16 text-center shadow-soft"><Label>[ CONTACT ] PROCHAINE ÉTAPE</Label><h2 className="mx-auto mt-4 max-w-2xl text-3xl font-bold sm:text-4xl">Un échantillon à analyser ? Parlons-en.</h2><div className="mt-8 flex flex-wrap justify-center gap-3"><Button size="lg" asChild><Link to="/contact">Demander un devis <ArrowRight/></Link></Button><Button size="lg" variant="outline" asChild><a href="tel:+212661361008">Appeler le +212 6 61 36 10 08</a></Button></div></div></section>}
export function DomainGrid({limit}:{limit?:number}){return <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{domains.slice(0,limit).map((d,i)=><Link key={d.slug} to="/prestations/$slug" params={{slug:d.slug}} className={`group relative min-h-80 overflow-hidden rounded-2xl ${i===0&&!limit?'lg:col-span-2 lg:row-span-2 lg:min-h-[42rem]':''}`}><img loading="lazy" src={d.image} alt={d.title} className="absolute inset-0 h-full w-full object-cover transition duration-500 group-hover:scale-105"/><div className="absolute inset-0 bg-linear-to-t from-navy via-navy/30 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6 text-primary-foreground"><d.icon className="mb-3 size-7 text-primary"/><h3 className="text-2xl font-bold">{d.title}</h3><p className="mt-2 text-sm text-primary-foreground/75">{d.short}</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-primary">Voir les analyses <ChevronRight className="size-4"/></span></div></Link>)}</div>}
