import { Link, useRouterState } from "@tanstack/react-router";
import { ArrowRight, ChevronDown, Menu, Phone, X } from "lucide-react";
import hero from "@/assets/hero-laboratoire.webp";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import logo from "@/assets/qualiup-logo.png.asset.json";
import { agencies, company, domains } from "@/data/site";

export function SiteHeader() {
  const [open,setOpen]=useState(false); const [scrolled,setScrolled]=useState(false);
  const path=useRouterState({select:s=>s.location.pathname});
  useEffect(()=>{ setOpen(false); window.scrollTo({top:0,behavior:"smooth"}); },[path]);
  useEffect(()=>{const fn=()=>setScrolled(window.scrollY>24);fn();addEventListener("scroll",fn,{passive:true});return()=>removeEventListener("scroll",fn)},[]);
  const nav=[['Accueil','/'],['À propos','/a-propos'],['Services','/services'],['Actualités','/actualites'],['Contact','/contact']] as const;
  return <>
    <div className="hidden bg-navy py-2 text-xs text-primary-foreground lg:block"><div className="container-site flex items-center justify-between"><span>{company.address}</span><div className="flex gap-6"><a href={`mailto:${company.email}`}>{company.email}</a><a href={`tel:${company.phoneHref}`}>{company.phone}</a></div></div></div>
    <header className={`sticky top-0 z-50 border-b transition-all ${scrolled?'glass border-border shadow-soft':'bg-background/95 border-transparent'}`}>
      <div className="container-site grid h-20 grid-cols-[minmax(0,1fr)_auto] items-center gap-4 lg:flex">
        <Link to="/" aria-label="QualiUp Group — Accueil" className="min-w-0"><img src={logo.url} alt="QualiUp Group" className="h-9 w-auto lg:h-11" /></Link>
        <nav className="mx-auto hidden items-center gap-1 lg:flex" aria-label="Navigation principale"><Link to="/" className="rounded-full px-3 py-2 text-sm font-semibold hover:bg-muted">Accueil</Link><div className="group/about relative"><Link to="/a-propos" className="rounded-full px-3 py-2 text-sm font-semibold hover:bg-muted">À propos <ChevronDown className="inline size-3"/></Link><div className="invisible absolute left-0 top-full mt-3 w-56 translate-y-2 rounded-2xl border bg-background p-3 opacity-0 shadow-float transition group-hover/about:visible group-hover/about:translate-y-0 group-hover/about:opacity-100 group-focus-within/about:visible group-focus-within/about:opacity-100"><Link to="/a-propos" className="block rounded-xl p-3 text-sm hover:bg-muted">À propos de nous</Link><Link to="/faq" className="block rounded-xl p-3 text-sm hover:bg-muted">FAQ</Link></div></div><div className="group/services"><Link to="/services" className="rounded-full px-3 py-2 text-sm font-semibold hover:bg-muted">Services <ChevronDown className="inline size-3"/></Link><div className="invisible absolute inset-x-0 top-full translate-y-2 border-y bg-background opacity-0 shadow-float transition group-hover/services:visible group-hover/services:translate-y-0 group-hover/services:opacity-100 group-focus-within/services:visible group-focus-within/services:opacity-100"><div className="container-site grid grid-cols-[1.4fr_.8fr_.8fr] gap-8 py-7"><div className="grid grid-cols-2 gap-2">{domains.map(d=><Link key={d.slug} to="/prestations/$slug" params={{slug:d.slug}} className="flex gap-3 rounded-xl p-3 hover:bg-muted"><d.icon className="mt-1 size-5 shrink-0 text-primary"/><span><b className="block text-sm">{d.title}</b><small className="text-muted-foreground">{d.short}</small></span></Link>)}</div><div className="border-l pl-7"><p className="font-mono text-xs text-primary">ACCOMPAGNEMENT</p><Link to="/conseil-formation" className="mt-4 block font-semibold">Conseil et Formation</Link><Link to="/audit-expertise" className="mt-4 block font-semibold">Audit et Expertise</Link><Link to="/services" className="mt-6 inline-flex items-center gap-2 text-sm text-secondary">Tous nos services <ArrowRight className="size-4"/></Link></div><div className="relative overflow-hidden rounded-2xl"><img src={hero} alt="" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-navy/70"/><div className="relative flex h-full flex-col justify-end p-5 text-white"><b>Besoin d’une analyse ?</b><Button className="mt-3" asChild><Link to="/contact">Demander un devis</Link></Button></div></div></div></div></div><Link to="/actualites" className="rounded-full px-3 py-2 text-sm font-semibold hover:bg-muted">Actualités</Link><Link to="/contact" className="rounded-full px-3 py-2 text-sm font-semibold hover:bg-muted">Contact</Link></nav>
        <div className="hidden items-center gap-3 lg:flex"><a className="text-sm font-semibold text-secondary" href={`tel:${company.phoneHref}`}><Phone className="mr-1 inline size-4"/>{company.phone}</a><Button asChild><Link to="/contact">Demander un devis</Link></Button></div>
        <Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setOpen(!open)} aria-label={open?"Fermer le menu":"Ouvrir le menu"}>{open?<X/>:<Menu/>}</Button>
      </div>
      {open&&<div className="fixed inset-x-0 top-20 bottom-0 overflow-y-auto bg-background p-6 lg:hidden"><nav className="flex flex-col gap-2">{nav.map(([label,to])=><Link key={to} to={to} className="border-b border-border py-4 font-display text-2xl font-bold">{label}</Link>)}<Link to="/prestations-analyses" className="py-3 text-secondary">Toutes les prestations d’analyses</Link>{domains.map(d=><Link key={d.slug} to="/prestations/$slug" params={{slug:d.slug}} className="py-1 text-sm text-muted-foreground">{d.title}</Link>)}<Button className="mt-6" asChild><Link to="/contact">Demander un devis</Link></Button><a className="mt-4 text-center font-semibold" href={`tel:${company.phoneHref}`}>{company.phone}</a></nav></div>}
    </header>
  </>;
}

export function SiteFooter(){return <footer className="relative overflow-hidden bg-navy py-16 text-primary-foreground"><div className="petri absolute inset-0 opacity-30"/><div className="container-site relative grid gap-10 md:grid-cols-2 lg:grid-cols-4"><div><div className="inline-block rounded-2xl bg-background px-4 py-3"><img src={logo.url} alt="QualiUp Group" className="h-11 w-auto"/></div><p className="mt-5 text-sm leading-7 text-primary-foreground/70">Depuis sa création en 2014, QualiUp s’affirme comme un véritable partenaire de l’industrie agroalimentaire.</p><a className="mt-3 block text-sm" href={`mailto:${company.email}`}>{company.email}</a><a className="mt-2 block text-sm" href={`tel:${company.phoneHref}`}>{company.phone}</a></div><FooterCol title="Liens utiles" links={[["À propos","/a-propos"],["FAQ","/faq"],["Contact","/contact"],["Actualités","/actualites"],["Tous nos services","/services"]]}/><div><h3 className="mb-5 text-lg">Nos prestations</h3><div className="space-y-2">{domains.map(d=><Link className="block text-sm text-primary-foreground/70 hover:text-primary" key={d.slug} to="/prestations/$slug" params={{slug:d.slug}}>{d.title}</Link>)}</div></div><div><h3 className="mb-5 text-lg">Nos agences</h3>{agencies.map(a=><div key={a.name} className="mb-4"><strong className="block text-sm">{a.name}</strong><a className="text-sm text-primary-foreground/70" href={`tel:${a.phone.replace(/\s/g,'')}`}>{a.phone}</a></div>)}</div></div><div className="container-site relative mt-12 flex flex-col gap-3 border-t border-primary-foreground/15 pt-6 text-xs text-primary-foreground/60 sm:flex-row sm:justify-between"><span>© 2026 QualiUp Group — Tous droits réservés</span><Link to="/mentions-legales">Mentions légales</Link></div></footer>}
function FooterCol({title,links}:{title:string;links:readonly (readonly [string,string])[]}){return <div><h3 className="mb-5 text-lg">{title}</h3>{links.map(([l,t])=><Link key={t} to={t} className="mb-3 block text-sm text-primary-foreground/70 hover:text-primary">{l}</Link>)}</div>}
